In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

import matplotlib.pyplot as plt
import seaborn as sns

import sklearn
from sklearn.linear_model import LinearRegression

sns.set_style('whitegrid')
%matplotlib inline

In [2]:
from sklearn.datasets import load_boston

In [3]:
boston = load_boston()

In [4]:
boston_df = DataFrame(boston.data)
boston_df.columns = boston.feature_names
boston_df.head(4)

boston_df['Price'] = boston.target
boston_df.head(4)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  Price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4

In [5]:
######################################################################################################
######################################################################################################
######################################################################################################

# Sem train and sem test values

In [6]:
import sklearn
from sklearn.linear_model import LinearRegression

In [7]:
X_multi = boston_df.drop('Price',1)
# 13 variables
Y_target = boston_df.Price

In [9]:
Y_target

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: Price, Length: 506, dtype: float64

In [8]:
model = LinearRegression()
model.fit(X_multi,Y_target)

LinearRegression()

In [9]:
predictions = model.predict(X_multi).dtype
predictions = model.predict(X_multi)
predictions

array([30.00384338, 25.02556238, 30.56759672, 28.60703649, 27.94352423,
       25.25628446, 23.00180827, 19.53598843, 11.52363685, 18.92026211,
       18.99949651, 21.58679568, 20.90652153, 19.55290281, 19.28348205,
       19.29748321, 20.52750979, 16.91140135, 16.17801106, 18.40613603,
       12.52385753, 17.67103669, 15.83288129, 13.80628535, 15.67833832,
       13.38668561, 15.46397655, 14.70847428, 19.54737285, 20.8764282 ,
       11.45511759, 18.05923295,  8.81105736, 14.28275814, 13.70675891,
       23.81463526, 22.34193708, 23.10891142, 22.91502612, 31.35762569,
       34.21510225, 28.02056414, 25.20386628, 24.60979273, 22.94149176,
       22.09669817, 20.42320032, 18.03655088,  9.10655377, 17.20607751,
       21.28152535, 23.97222285, 27.6558508 , 24.04901809, 15.3618477 ,
       31.15264947, 24.85686978, 33.10919806, 21.77537987, 21.08493555,
       17.8725804 , 18.51110208, 23.98742856, 22.55408869, 23.37308644,
       30.36148358, 25.53056512, 21.11338564, 17.42153786, 20.78

In [10]:
coefficient_y = model.intercept_
coefficient_y
# Axis independent

36.459488385089855

In [11]:
coefficient_x = model.coef_
coefficient_x
# Angular coefficient

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [12]:
coeff_df = DataFrame(boston_df.columns)
coeff_df 

coeff_df.columns = ['Features']

coeff_df['Coeffcient Estimate'] = Series(model.coef_)

coeff_df

Features  Coeffcient Estimate
0      CRIM            -0.108011
1        ZN             0.046420
2     INDUS             0.020559
3      CHAS             2.686734
4       NOX           -17.766611
5        RM             3.809865
6       AGE             0.000692
7       DIS            -1.475567
8       RAD             0.306049
9       TAX            -0.012335
10  PTRATIO            -0.952747
11        B             0.009312
12    LSTAT            -0.524758
13    Price                  NaN

In [13]:
######################################################################################################
######################################################################################################
######################################################################################################

# Train and Test values

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_multi ,Y_target, test_size=0.2, random_state=101)

In [27]:
print(len(X_train))
print(len(X_test))

print(len(y_train))
print(len(y_test))

404
102
404
102


In [28]:
X_train.shape

(404, 13)

In [29]:
y_train.shape

(404,)

In [30]:
X_multi.shape

(506, 13)

In [31]:
Y_target.shape

(506,)

In [32]:
X_multi = boston_df.drop('Price',1)
X_multi

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [33]:
Y_target = boston_df.Price
Y_target

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: Price, Length: 506, dtype: float64

In [34]:
X_multi = boston_df.drop('Price',1)
# 13 variables

Y_target = boston_df.Price

In [35]:
my_model = LinearRegression()

my_model.fit(X_train ,y_train)

LinearRegression()

In [36]:
my_model.predict(X_test)

array([40.38909533, 27.88818526, 16.33126585, 17.34675932, 30.91273758,
       32.82478967, 39.95560959,  8.4519632 , 33.28696607,  7.26751237,
       29.77875241, 13.70647921, 16.10840816, 16.65150567, 25.03371365,
       19.89032014,  6.79501283, 32.9949698 , 28.45233055, 24.72790211,
       12.81760374, 20.2792643 , 22.37316895, 24.95238223, 34.01786165,
       19.10866644, 31.80654265, 19.09506858, 26.40103588, 34.13083397,
       19.66337036, 18.24445944, 36.99113563, 44.48687324, 30.72146569,
       22.31475986, 16.17389267, 17.91169858,  4.80466972, 30.60025057,
       23.92860043, 16.46250167, 35.26168512, 13.85353888, 17.81678796,
       25.33703575, 30.79303765, 16.47025922, 26.65460208, 23.15784888,
       32.62443559, 38.6798773 , 22.21243126, 15.78598365, 30.5359631 ,
       -0.25281891, 20.07283762, 16.83546069, 22.54691328, 20.67388019,
       30.46894504,  3.38104287, 13.94720253, 19.46240302, 10.03614762,
       24.67738776, 24.20357095, 19.43161581, 18.3602221 , 19.03

In [38]:
Y_0 = my_model.predict(X_test)
Y_0 

array([40.38909533, 27.88818526, 16.33126585, 17.34675932, 30.91273758,
       32.82478967, 39.95560959,  8.4519632 , 33.28696607,  7.26751237,
       29.77875241, 13.70647921, 16.10840816, 16.65150567, 25.03371365,
       19.89032014,  6.79501283, 32.9949698 , 28.45233055, 24.72790211,
       12.81760374, 20.2792643 , 22.37316895, 24.95238223, 34.01786165,
       19.10866644, 31.80654265, 19.09506858, 26.40103588, 34.13083397,
       19.66337036, 18.24445944, 36.99113563, 44.48687324, 30.72146569,
       22.31475986, 16.17389267, 17.91169858,  4.80466972, 30.60025057,
       23.92860043, 16.46250167, 35.26168512, 13.85353888, 17.81678796,
       25.33703575, 30.79303765, 16.47025922, 26.65460208, 23.15784888,
       32.62443559, 38.6798773 , 22.21243126, 15.78598365, 30.5359631 ,
       -0.25281891, 20.07283762, 16.83546069, 22.54691328, 20.67388019,
       30.46894504,  3.38104287, 13.94720253, 19.46240302, 10.03614762,
       24.67738776, 24.20357095, 19.43161581, 18.3602221 , 19.03

In [20]:
my_model.intercept_

32.90613090863722

In [21]:
my_model.coef_

array([-9.89913563e-02,  4.25047578e-02,  1.67390094e-02,  3.06437882e+00,
       -1.56462528e+01,  4.01888422e+00, -8.31558474e-04, -1.44628034e+00,
        2.67827281e-01, -1.04725485e-02, -8.88651815e-01,  8.25262805e-03,
       -5.49367192e-01])

In [22]:
r2_score = my_model.score(X_test,y_test)
print(r2_score*100,'%')

70.34623076515885 %


In [23]:
######################################################################################################
######################################################################################################
######################################################################################################

In [53]:
height = [172,187,153,183,173,173,176,173,160,175,182,165,165,170,170,159,195,162,166,172,168]
weight = [62,98,70,90,68,53,52,56,50,87,10,72,68,80,59,63,12,53,63,65,67]
sex = ['Male','Male','Female','Male','Female','Female','Female','Female','Female','Male','Male','Male','Male','Male','Female','Female','Male','Male','Male','Female','Female']
sex = [0,0,1,0,1,1,1,1,1,0,0,0,0,0,1,1,0,0,0,1,1]

In [54]:
# https://medium.com/@diegosantosseabra/scikit-learn-python-linear-regression-predicting-the-sex-of-a-person-df72700a0732

In [55]:
# https://towardsdatascience.com/linear-regression-in-real-life-4a78d7159f16

In [58]:
df = pd.read_csv('People_Data.csv', index_col=0)
df

height  weight  sex
0      172      62    0
1      187      98    0
2      153      70    1
3      183      90    0
4      173      68    1
5      173      53    1
6      176      52    1
7      173      56    1
8      160      50    1
9      175      87    0
10     182      10    0
11     165      72    0
12     165      68    0
13     170      80    0
14     170      59    1
15     159      63    1
16     195      12    0
17     162      53    0
18     166      63    0
19     172      65    1
20     168      67    1

In [59]:
X = df[['weight', 'height']]
Y = df[['sex']]

In [87]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X ,Y, test_size=0.3, random_state=101)

In [88]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [89]:
predictions = model.predict(X_test)

In [90]:
r2_score = model.score(X_test,y_test)
print(r2_score*100,'%')

34.13510479659298 %


In [95]:
myvals = np.array([94, 182]).reshape(1, -1)
print(model.predict(myvals)) 

# The more close to 0, the more is a Male
# The more close to 1, the more is a Female

[[0.18185029]]


In [42]:
######################################################################################################

In [43]:
from sklearn import metrics

In [ ]:
print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))